# Generated by Django 4.1.1 on 2022-09-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destiantion',
            new_name='destination',
        ),
    ]
